export default class PROTOCLE {
  static CLIENT = {
    MATCH: "MATCH",
    RECONNECT: "RECONNECT",
    ANNOUNCE: "ANNOUNCE",
    VOTE: "VOTE",
    CHAT: "CHAT",
    FINISH_TASK: "FINISH_TASK",
    DO_TASK13:'DO_TASK13',
    KILL: "KILL",
    DESTROY: "DESTROY",
    JUMP_UNDER: "JUMP_UNDER",
    UPDATE_LOCATION: "UPDATE_LOCATION",
    PLAY_ANIMATION: "PLAY_ANIMATION",
    UPDATE_USER_DATA: "UPDATE_USER_DATA",
    GAME_START: "GAME_START",
    UNDER: "UNDER",
    PING: "PING",
    KILLER_DO_DESTROY: "KILLER_DO_DESTROY",
    DESTROY_FIXED: "DESTROY_FIXED",
    EXIT:'EXIT',
  };
  static SERVER = {
    EXIT:'EXIT',
    TASK_FINISH: "TASK_FINISH",
    DESTROY_FIXED: "DESTROY_FIXED",
    KILLER_DO_DESTROY: "KILLER_DO_DESTROY",
    EMER_MEETING: "EMER_MEETING",
    SHOW_VOTED_RESULT: "SHOW_VOTED_RESULT",
    KILL: "KILL",
    VOTED_MAP: "VOTED_MAP",
    SEARCHING: "SEARCHING",
    MATCH: "MATCH",
    RECONNECT: "RECONNECT",
    ANNOUNCE: "ANNOUNCE",
    ERROR: "ERROR",

    MATCH_RESULT: "MATCH_RESULT",
    // 聊天
    CHAT: "CHAT",
    // 更新队列数据
    WAITING_LIST_UPDATE: "WAITING_LIST_UPDATE",
    // 开始游戏
    GAME_START: "GAME_START",
    GAME_PRESTART: "GAME_PRESTART",
    GAME_PRESTART_CANCEL: "GAME_PRESTART_CANCEL",
    UPDATE_GAME_LIST: "UPDATE_GAME_LIST",
    UPDATE_USER_INFO: "UPDATE_USER_INFO",
    VOTED_RESULT: "VOTED_RESULT",
    RESULT: "RESULT",
    UPDATE_LOCATION: "UPDATE_LOCATION",
    PLAY_ANIMATION: "PLAY_ANIMATION",
    UPDATE_USER_DATA: "UPDATE_USER_DATA",
    UNDER: "UNDER",
    GAME_TASK_PROGRESS: "GAME_TASK_PROGRESS",
    PING: "PING"
  };
}
